# Railway Frontend Service Configuration

# Build configuration
[build]
  command = "yarn install && yarn build"
  
# Start configuration  
[start]
  command = "yarn start"

# Environment variables
[env]
  NODE_ENV = "production"
  REACT_APP_SUPABASE_URL = "https://pmfwqmaykidbvjhcqjrr.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtZndxbWF5a2lkYnZqaGNxanJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDk2MjUsImV4cCI6MjA2Nzk4NTYyNX0.BsJ0128ME7WhH-CBRb3_LTV5NvsDkVev07SzOalAb-E"
  REACT_APP_BACKEND_URL = "https://your-backend-service.railway.app"

# Service configuration
[service]
  port = 3000
  healthcheck = "/api/health"